// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PROJECT_NAME = 'books_mobile_app';
  static const String PROJECT_VERSION = '1.0.0+1';
  static const String APPLEICON = 'assets/images/icons/appleIcon.svg';
  static const String GOOGLEICON = 'assets/images/icons/googleIcon.svg';
  static const String ONBOOARDIGIMG1 = 'assets/images/onboarding/onbooardigimg1.png';
  static const String ONBOOARDIGIMG2 = 'assets/images/onboarding/onbooardigimg2.png';
  static const String ONBOOARDIGIMG3 = 'assets/images/onboarding/onbooardigimg3.png';
}
